### PR TITLE
r_Pony_irl and r_CursedComments

### PR DESCRIPTION
**Pull request by baatochan**
# PR Details

## Subreddit

* Pony_irl
* cursedcomments

## Telegram Channel

* @r_Pony_irl
* @r_CursedComments

## Checklist

- [x] Added `channels/%submodule_name%/app.py` file.
- [x] Added `channels/%submodule_name%/__init__.py` file.
- [x] Added `channels/%submodule_name%/tags.txt` file.
- [x] Updated `README.md`.
- [ ] Updated `own.cron`.
- [x] Already have nice channel's profile pic.
- [x] Already have mentioned `@r_channels` and `@reddit2telegram` in the description of your channel.
- [x] `@reddit2telegram_bot` added as admin to this channel.

* `%submodule_name%` should be in lowercase.
* Tags in `tags.txt` should be space-separeted and start with `#` each.

### CODE REVIEW

**Comment by Fillll** [comment]
r_pony channel is not exists. So deactivating.

**Comment by baatochan** [comment]
There was mistake on my end (wrong tg chanel name). Now everything should be okay.

**Comment by Fillll** [comment]
What is the right one?

**Comment by baatochan** [comment]
Exactly as in the commit. If you run it now, it should work.

**Pull request merged**
