### PR TITLE
Add r/traphentai

### PR DESCRIPTION
**Pull request by RDKRACZ**
# PR Details

## Subreddit

_What subreddit?_
r/traphentai
## Telegram Channel

_What telegram channel?_
@reddit_traphentai
## Checklist

- [x] Added `channels/%submodule_name%/app.py` file.
- [x] Added `channels/%submodule_name%/__init__.py` file.
- [x] Added `channels/%submodule_name%/tags.txt` file.
- [ ] Updated `own.cron`.
- [x] Already have nice channel's profile pic.
- [x] Already have mentioned `@r_channels` and `@reddit2telegram` in the description of your channel.
- [x] `@reddit2telegram_bot` added as admin to this channel.

* `%submodule_name%` should be in lowercase.
* Tags in `tags.txt` should be space-separeted and start with `#` each.

### CODE REVIEW

**Comment by Fillll** [comment]
Does channel `@r_traphentai` exist?

**Comment by RDKRACZ** [comment]
[yes](https://t.me/r_traphentai)

**Comment by Fillll** [comment]
not allowed
image

**Comment by RDKRACZ** [comment]
Hello, I created new channel and updated the PR.

**Comment by Fillll** [comment]
Is it still pornographic?

**Comment by RDKRACZ** [comment]
Yes.
Is this a problem? I don't see any mention that NSFW is disallowed in the readme.

**Comment by Fillll** [comment]
Yes, Telegram has issues with porn on iOS. Hence we do not want get into this area.

**Pull request closed without merging**
