### PR TITLE
New Channel

### PR DESCRIPTION
**Pull request by mshafiei**
Hi, I made some changes to add my channel. The subreddit is private though. I'm not sure how I should give the bot an access. Any idea?

### CODE REVIEW

**Comment by mshafiei** [comment]
sure, but what is the bot's username in reddit? is it /u/fillll? or /u/reddit2telegram?

**Comment by mshafiei** [comment]
any idea?

**Comment by Fillll** [comment]
Hm.... Let's try with `/u/reddit2telegram_bot`.

**Comment by Fillll** [comment]
@mshafiei let me know, when done

**Comment by mshafiei** [comment]
Done :)

**Comment by mshafiei** [comment]
It works like a charm. Thanks again.
Is there any way to get updates for the replies as well?

**Comment by Fillll** [comment]
48208c74a81224ab7bb4a00a13d158a490adb96c

**Comment by Fillll** [comment]
Please add `@r_channels` to your channel description.

**Pull request closed without merging**
