### PR TITLE
Updated pytgbot and removed duplicate code.

### PR DESCRIPTION
**Pull request by luckydonald**
Resolves the errors of **r_unexpected** in https://github.com/Fillll/reddit2telegram/pull/9

### CODE REVIEW

**Comment by luckydonald** [comment]
This time it's tested.
screen shot 2016-10-13 at 01 05 20

**Comment by Fillll** [comment]
Merged.

Still some issues.

``` bash
http://redd.it/574z56
text/html; charset=utf-8
Traceback (most recent call last):
  File "main_app.py", line 49, in <module>
    main()
  File "main_app.py", line 45, in main
    supply(args.sub, config)
  File "main_app.py", line 31, in supply
    success = submodule.send_post(submission, bot)
  File "/home/olive/reddit2telegram/channels/r_unexpected/app.py", line 32, in send_post
    bot.send_document(t_channel, document=gif_url, caption=text)
  File "/home/olive/reddit2telegram/env/lib/python3.5/site-packages/pytgbot/bot.py", line 608, in send_document
    reply_markup=reply_markup
  File "/home/olive/reddit2telegram/env/lib/python3.5/site-packages/pytgbot/bot.py", line 2287, in _do_fileupload
    return self.do("send{cmd}".format(cmd=file_param_name.capitalize()), **kwargs)
  File "/home/olive/reddit2telegram/env/lib/python3.5/site-packages/pytgbot/bot.py", line 2187, in do
    return self._postprocess_request(r)
  File "/home/olive/reddit2telegram/env/lib/python3.5/site-packages/pytgbot/bot.py", line 2246, in _postprocess_request
    request=r.request
pytgbot.exceptions.TgApiServerException: TgApiServerException(error_code=400, response=<Response [400]>, description='Wrong file identifier/HTTP URL specified', request=<PreparedRequest [POST]>)
```

Set it to xx:45 every 3 hours. If you want smth else — let me know.

**Comment by luckydonald** [comment]
Thats the Telegram Server responding it doesn't like the image URL...

**Comment by luckydonald** [comment]
Can you turn on debug (with `level=INFO`)?
```python
# add this to the first lines in your file (main_app.py)
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by Fillll** [comment]
Set it to xx:45 **every 1 hours**.

Will add logging level a little later.

**Comment by luckydonald** [comment]
Okey, Sentry support instead :D

**Pull request merged**
