### PR TITLE
Add /r/AskMen

### PR DESCRIPTION
**Pull request by infinity-plus**
# PR Details

## Subreddit

_What subreddit?_
[/r/AskMen](https://www.reddit.com/r/askmen/)

## Telegram Channel

_What telegram channel?_
[@r_askmen](https://t.me/r_askmen) 

## Checklist

- [x] Added `channels/%submodule_name%/app.py` file.
- [x] Added `channels/%submodule_name%/__init__.py` file.
- [x] Added `channels/%submodule_name%/tags.txt` file.
- [ ] Updated `own.cron`.
- [x] Already have nice channel's profile pic.
- [x] Already have mentioned `@r_channels` and `@reddit2telegram` in the description of your channel.
- [x] `@reddit2telegram_bot` added as admin to this channel.

* `%submodule_name%` should be in lowercase.
* Tags in `tags.txt` should be space-separeted and start with `#` each.

### CODE REVIEW

**Comment by infinity-plus** [comment]
`channels/r_askmen/tags.txt`  is empty, awaiting instructions as subreddit probably does not have flairs.

**Comment by Fillll** [comment]
It’s not about flairs, but just a list of tags which you think will describe the channel.

**Comment by infinity-plus** [comment]
Done, please see further.

**Comment by Fillll** [comment]
Looks good.

**Pull request merged**
