### PR TITLE
r/FreeGamesOnSteam

### PR DESCRIPTION
**Pull request by baatochan**

### CODE REVIEW

**Comment by Fillll** [comment]
It is ok. But what was your template?

**Comment by baatochan** [comment]
I did this template myself for r/slimerancher. Then I used the same one for r/techSupportGore and r/animeirl. And now for that.

**Comment by Fillll** [comment]
You can use new example. Much more easy.
https://github.com/Fillll/reddit2telegram/blob/master/channels/r_funny/app.py

**Comment by baatochan** [comment]
it's easier but it doesn't offer as much customization of text as i did here. i mean i know i can do the same customization in that template as well but i don't fully understand everything here and it may take some time for me (especially as i dont have any way to test other than pushing changes via pr and seeing what happens)

**Comment by Fillll** [comment]
No problem. Just letting you know, in case you missed it.

**Pull request merged**
